development:
  adapter: sqlserver
  host: 10.12.18.14
  database: rtstaged
  username: reader_admin
  password: reader


# test:
#   adapter: postgresql
#   encoding: unicode
#   database: reader_tool_test
