common: &shared
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  encoding: unicode

development:
  database: reader_tool_development
  <<: *shared


test:
  database: reader_tool_test
  <<: *shared
